SistemaMarketPlacePIMVIII/Models/Carrinho.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class Carrinho
    {
        [Key]
        [Column(Order = 1)]
        public int ID { get; set; }
        public DateTime Data_Pedido { get; set; }
        public decimal Valor_total { get; set; }
        public int Status_Pedido_Id { get; set; }
        public Cliente? Cliente { get; set; }
        public int Client_Id { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class Cliente
    {
        [Key]
        [Column(Order = 1)]
        public int ID { get; set; }
        public string Nome { get; set; }
        public long CPF { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public int Endereco_ID { get; set; }
        public Vendedor Endereco { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/Endereco.cs
namespace SistemaMarketPlacePIMVIII.Models
{
    public class Endereco
    {
        public int ID { get; set; }
        public string CEP { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/Item_Carrinho.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class Item_Carrinho
    {
        [Key]
        public int Carrinho_ID { get; set; }
        public Carrinho Carrinho { get; set; }
        public int Produto_ID { get; set; }
        public Produto Produto { get; set; }
        public string Quantidade { get; set; }
        public decimal Total { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/Item_CarrinhoModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class Item_CarrinhoModel
    {
        public string Quantidade { get; set; }
        public decimal Total { get; set; }

        // Relacionamentos com Carrinho e Produto
        [Key]
        [Column(Order = 1)]
        [ForeignKey(nameof(CarrinhoModel))]
        public int Carrinho_ID { get; set; }
        //public CarrinhoModel Carrinho { get; set; }

        [Key]
        [Column(Order = 2)]
        [ForeignKey(nameof(ProdutoModel))]
        public int Produto_ID { get; set; }
        //public ProdutoModel Produto { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class Produto
    {
        [Key]
        [Column(Order = 1)]
        public int ID { get; set; }
        public string Descricao { get; set; }
        public decimal Preco { get; set; }
        public string Imagem { get; set; }
        public bool Status { get; set; }
        public int Vendedor_ID { get; set; }
        public int Categoria_ID { get; set; }
        public Vendedor Vendedor { get; set; }
        public Categoria Categoria { get; set; }

    }
    public class Categoria
    {
        [Key]
        [Column(Order = 1)]
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/ProdutoModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class ProdutoModel
    {
        [Key]
        public int ID { get; set; }
        public string Descricao { get; set; }
        public decimal Preco { get; set; }
        public string Imagem { get; set; }
        public bool Status { get; set; }
        public int Vendedor_ID { get; set; }
        public int Categoria_ID { get; set; }

        // Relacionamentos com Vendedor e Categoria
        public VendedorModel Vendedor { get; set; }
        public string Categoria { get; set; }

    }
}

SistemaMarketPlacePIMVIII/Models/Vendedor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class Vendedor
    {
        [Key]
        [Column(Order = 1)]
        public int ID { get; set; }
        public string Razao_Social { get; set; }
        public string Nome_Fantasia { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string CNPJ { get; set; }
        public int Comissao { get; set; }
        public Endereco Endereco_ID { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Models/VendedorModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaMarketPlacePIMVIII.Models
{
    public class VendedorModel
    {
        [Key]
        public int ID { get; set; }
        public string Razao_Social { get; set; }
        public string Nome_Fantasia { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string CNPJ { get; set; }
        public int Comissao { get; set; }
        public int Endereco_ID { get; set; }
    }
}

SistemaMarketPlacePIMVIII/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaMarketPlacePIMVIII.Models;
using SistemaMarketPlacePIMVIII.Repositories;
using System.Diagnostics;

namespace SistemaMarketPlacePIMVIII.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemaMarketPlacePIMVIII/Controllers/LojaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaMarketPlacePIMVIII.Controllers
{
    public class LojaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Carrinho()
        {
            return View();
        }
    }
}

SistemaMarketPlacePIMVIII/Views/Home/Index.cshtml
@model List<Carrinho>
@{
    ViewData["Title"] = "Home Page";
}

{
    <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaMarketPlacePIMVIII/Views/Loja/Carrinho.cshtml
@{
    ViewData["Title"] = "Meu Carrinho";
}

<link href="~/css/carrinho.css" rel="stylesheet" />
<main>
    <div class="page-title">Seu Carrinho</div>
    <div class="content">
        <button class="btn btn-success" onclick="addProdutoNovo()">Adicionar produto</button>
        <section>
            <table>
                <thead>
                    <tr>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th>Quantidade</th>
                        <th>Total</th>
                        <th>-</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </section>
        <aside>
            <div class="box">
                <header>Resumo da compra</header>
                <div class="info">
                    <div><span>Sub-total</span><span>R$ 0</span></div>
                    <div><span>Frete</span><span>R$ 0</span></div>
                    <div>
                        <button>
                            Adicionar cupom de desconto
                            <i class="bx bx-right-arrow-alt"></i>
                        </button>
                    </div>
                </div>
                <footer>
                    <span>Total</span>
                    <span>R$ 0</span>
                </footer>
            </div>
            <button>Finalizar Compra</button>
        </aside>
    </div>
</main>

SistemaMarketPlacePIMVIII/Views/Loja/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

SistemaMarketPlacePIMVIII/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaMarketPlacePIMVIII</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaMarketPlacePIMVIII.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaMarketPlacePIMVIII</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loja" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loja" asp-action="Carrinho">Carrinho</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaMarketPlacePIMVIII - <a asp-area="" asp-controller="Loja" asp-action="Index">Página Inicial</a>
        </div>
    </footer>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>